language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_996b9d9f09fe_key -iv $encrypted_996b9d9f09fe_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
