# Generated by Django 2.0.7 on 2018-07-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
    ]
